"""empty message

Revision ID: ad936e8e7a43
Revises: c5a60a15d183
Create Date: 2023-07-20 22:33:09.852883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad936e8e7a43'
down_revision = 'c5a60a15d183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('max_atmospherix_speed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_atmospherix_speed', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
