"""empty message

Revision ID: bcc1f4d3c1b2
Revises: 0328f6cec941
Create Date: 2023-07-13 05:05:14.862743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc1f4d3c1b2'
down_revision = '0328f6cec941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('films')
        batch_op.drop_column('starships')
        batch_op.drop_column('vehicles')
        batch_op.drop_column('species')

    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_character_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_character_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.create_foreign_key('favorite_character_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_character_character_id_fkey', 'character', ['character_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicles', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('starships', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('films', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
